AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Metadata:
  AWS::ServerlessRepo::Application:
    Name: mongodb-atlas-kinesis-data-firehose-api
    Description: >
      This is a SAM project for a Python MongoDB Kinesis Data Firehose API.
    Author: MongoDb
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE.txt
    ReadmeUrl: readme.md
    Labels: ['Mongodb']
    HomePageUrl: https://github.com/mongodb-partners/MongoDB-Kinesis-Transformation
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/mongodb-partners/MongoDB-Kinesis-Transformation
Parameters:

  ConnectionString:
    Type: String
    Description: >
      The connection string for MongoDB Atlas.
    Default: ""

  DBName:
    Type: String
    Description: >
      Mongodb database name
    Default: "test"

  CollectionName:
    Type: String
    Description: >
      Mongodb collection name, where you want to save data
    Default: "test"


Resources:
  AuthorizerLambda:
      Type: AWS::Serverless::Function
      Properties:
        Runtime: python3.10
        Timeout: 15
        CodeUri: ./authorizer/
        Handler: app.lambda_handler
        Environment:
          Variables:
            VALID_KEYS: "FIXME"

  CRUDLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.10
      Timeout: 15
      CodeUri: ./lambda/
      Handler: app.lambda_handler
      Environment:
        Variables:
          ATLAS_CONNECTION_STRING: !Ref ConnectionString
          COLLECTION_NAME: !Ref CollectionName
          DB_NAME: !Ref DBName
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
      Events:
        GetEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRest
            Path: /
            Method: ANY
            Auth:
              ApiKeyRequired: true

  ServerlessRest:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          Description: Usage plan for this API
          Quota:
            Limit: 500
            Period: MONTH
          Throttle:
            BurstLimit: 100
            RateLimit: 50
        Authorizers:
          LambdaRequestAuthorizer:
            FunctionArn: !GetAtt AuthorizerLambda.Arn  # Reference to your Lambda function
            Identity:
              Headers:
                - X-Amz-Firehose-Access-Key  # The header containing the token
            AuthorizerResultTtlInSeconds: 300  # Cache authorization results for 5 minutes
            FunctionPayloadType: REQUEST       # Can be TOKEN or REQUEST
        DefaultAuthorizer: LambdaRequestAuthorizer  # Makes this the default authorizer for all routes



Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRest}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ApiKeyValue:
    Description: API Key
    Value: !Sub "key: ${ServerlessRestApiKey}"
  ApiKeyUrl:
    Description: "Key URL"
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/apigateway/main/api-keys/${ServerlessRestApiKey}?api=unselected&region=${AWS::Region}"
  